name: C/C++ CI

on: [push]

jobs:
  Spicy-build:
  - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.9'
        host: 'linux'
        target: 'desktop'
        dir: '${{ github.workspace }}/src/'
        install-deps: 'true'
