name: C/C++ CI

on: [push]

jobs:
  Spicy-build:
    runs-on: ubuntu-latest
    container:
      image: rabits/qt:5.14-desktop
      options: --user 1001
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1
      with:
        submodule_update: ON
        run_tests: ON
        #unit_test_build: -Dtest=ON
