name: C/C++ CI

on: [push]

jobs:
  Spicy-build:
    runs-on: windows-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.4'
        host: 'windows'
        target: 'desktop'
        py7zrversion: '==0.10.1'
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Debug
